"""webhook subscriptions

Revision ID: 12be67633483
Revises: bc0c2b9de666
Create Date: 2026-01-11 10:23:55.436575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12be67633483'
down_revision: Union[str, Sequence[str], None] = 'bc0c2b9de666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_project_id'), 'webhook_subscriptions', ['project_id'], unique=False)
    op.create_index('ix_webhooks_project_enabled', 'webhook_subscriptions', ['project_id', 'enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhooks_project_enabled', table_name='webhook_subscriptions')
    op.drop_index(op.f('ix_webhook_subscriptions_project_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    # ### end Alembic commands ###
