"""make timestamps timezone aware

Revision ID: 1e67dc3a2804
Revises: f68fc9f4d218
Create Date: 2026-01-11 13:32:27.163678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e67dc3a2804'
down_revision: Union[str, Sequence[str], None] = 'f68fc9f4d218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'triggered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="triggered_at AT TIME ZONE 'UTC'",)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('api_keys', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="revoked_at AT TIME ZONE 'UTC'",)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",)
    op.alter_column('devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('orgs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('telemetry_events', 'ts',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="ts AT TIME ZONE 'UTC'",)
    op.alter_column('telemetry_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('webhook_deliveries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('webhook_deliveries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",)
    op.alter_column('webhook_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using="delivered_at AT TIME ZONE 'UTC'",)
    op.execute("DROP INDEX IF EXISTS ix_delivery_project_id")
    op.create_index(op.f('ix_webhook_deliveries_project_id'), 'webhook_deliveries', ['project_id'], unique=False)
    op.alter_column('webhook_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_subscriptions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.drop_index(op.f('ix_webhook_deliveries_project_id'), table_name='webhook_deliveries')
    op.create_index(op.f('ix_delivery_project_id'), 'webhook_deliveries', ['project_id'], unique=False)
    op.alter_column('webhook_deliveries', 'delivered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
                postgresql_using="delivered_at AT TIME ZONE 'UTC'",)
    op.alter_column('webhook_deliveries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="updated_at AT TIME ZONE 'UTC'",)
    op.alter_column('webhook_deliveries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('telemetry_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('telemetry_events', 'ts',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="ts AT TIME ZONE 'UTC'",)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('orgs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('devices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
                postgresql_using="last_used_at AT TIME ZONE 'UTC'",)
    op.alter_column('api_keys', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
                postgresql_using="revoked_at AT TIME ZONE 'UTC'",)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
                postgresql_using="created_at AT TIME ZONE 'UTC'",)
    op.alter_column('alerts', 'triggered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
                postgresql_using="triggered_at AT TIME ZONE 'UTC'",)
    # ### end Alembic commands ###
