"""webhook subscriptions

Revision ID: bc0c2b9de666
Revises: 0103978571d1
Create Date: 2026-01-11 10:20:23.376480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0c2b9de666'
down_revision: Union[str, Sequence[str], None] = '0103978571d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_tags_gin'), table_name='devices', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_tags_gin'), 'devices', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
